### ISSUE TITLE
Bug: Crash when loading on server 

### ISSUE THREAD

**Issue by schindlershadow** [0999312/umapyoi#43]
### Describe the bug

Crash when loading on server 

### Steps to reproduce

Load mod in server

### Expected behavior

mod does not cause crash report

### Versions

- OS: linux
- Launcher: neoforge 21.1.42
- Java version: openjdk 21.0.4
- Minecraft version: 1.21.1
- Umapyoi version: umapyoi-1.0.0-1.21

### Additional context

```
Time: 2024-09-17 23:24:01
Description: Exception in server tick loop

java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at TRANSFORMER/umapyoi@1.0.0-1.21/net.tracen.umapyoi.UmapyoiCreativeGroup.fillUmaSoul(UmapyoiCreativeGroup.java:72) ~[umapyoi-1.0.0-1.21.jar%23521!/:?] {re:classloading}
	at TRANSFORMER/umapyoi@1.0.0-1.21/net.tracen.umapyoi.UmapyoiCreativeGroup.lambda$static$0(UmapyoiCreativeGroup.java:43) ~[umapyoi-1.0.0-1.21.jar%23521!/:?] {re:classloading}
	at java.base/java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:729) ~[?:?] {}
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[?:?] {}
	at TRANSFORMER/umapyoi@1.0.0-1.21/net.tracen.umapyoi.UmapyoiCreativeGroup.lambda$static$1(UmapyoiCreativeGroup.java:37) ~[umapyoi-1.0.0-1.21.jar%23521!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.event.EventHooks.onCreativeModeTabBuildContents(EventHooks.java:1090) ~[neoforge-21.1.42-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTab.buildContents(CreativeModeTab.java:145) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTabs.lambda$buildAllTabContents$48(CreativeModeTabs.java:2166) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTabs.buildAllTabContents(CreativeModeTabs.java:2166) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTabs.tryRebuildTabContents(CreativeModeTabs.java:2177) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.CommonHooks.onServerStarted(CommonHooks.java:78) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23355!/:1.113.1] {re:classloading}
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.ForgeCommonHooks.onServerStarted(ForgeCommonHooks.java:53) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23355!/:1.113.1] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%2367!/:?] {}
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:114) ~[neoforge-21.1.42-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

**Comment by 0999312** [comment]
Try 1.0.1-1.21

**Comment by schindlershadow** [comment]
still crashes
```
Time: 2024-09-18 18:54:49
Description: Exception in server tick loop

java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at TRANSFORMER/umapyoi@1.0.1-1.21/net.tracen.umapyoi.UmapyoiCreativeGroup.fillUmaSoul(UmapyoiCreativeGroup.java:72) ~[umapyoi-1.0.1-1.21.jar%23521!/:?] {re:classloading}
	at TRANSFORMER/umapyoi@1.0.1-1.21/net.tracen.umapyoi.UmapyoiCreativeGroup.lambda$static$0(UmapyoiCreativeGroup.java:43) ~[umapyoi-1.0.1-1.21.jar%23521!/:?] {re:classloading}
	at java.base/java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:729) ~[?:?] {}
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[?:?] {}
	at TRANSFORMER/umapyoi@1.0.1-1.21/net.tracen.umapyoi.UmapyoiCreativeGroup.lambda$static$1(UmapyoiCreativeGroup.java:37) ~[umapyoi-1.0.1-1.21.jar%23521!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.event.EventHooks.onCreativeModeTabBuildContents(EventHooks.java:1090) ~[neoforge-21.1.42-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTab.buildContents(CreativeModeTab.java:145) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTabs.lambda$buildAllTabContents$48(CreativeModeTabs.java:2166) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTabs.buildAllTabContents(CreativeModeTabs.java:2166) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.CreativeModeTabs.tryRebuildTabContents(CreativeModeTabs.java:2177) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.CommonHooks.onServerStarted(CommonHooks.java:78) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23355!/:1.113.1] {re:classloading}
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.ForgeCommonHooks.onServerStarted(ForgeCommonHooks.java:53) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23355!/:1.113.1] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%2367!/:?] {}
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:114) ~[neoforge-21.1.42-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

also that version is not marked as 1.21.1 on curseforge

**Comment by 0999312** [comment]
Bug fixed in 1.0.2-1.21
